name: Run PHPUnit Tests

on:
  push:
    branches: main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysqli
          coverage: none
          
      - name: Clear Composer Cache
        run: composer clear-cache
      - name: List vendor directory
        run: ls -la /home/runner/work/sofistia-back-end/sofistia-back-end/vendor/phpunit/phpunit/
      
      - name: Check permissions
        run: stat /home/runner/work/sofistia-back-end/sofistia-back-end/vendor/phpunit/phpunit/src/

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --verbose

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
